-- ==============================================================================
-- ALERTA CIUDADANA - ESQUEMA DE BASE DE DATOS POSTGRESQL / SUPABASE
-- ==============================================================================

-- 1. Tabla PERSONA (Ciudadanos registrados)
CREATE TABLE IF NOT EXISTS persona (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(15) UNIQUE NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    direccion VARCHAR(255),
    password_hash VARCHAR(255), -- Contraseña de acceso a la app móvil
    pin_hash VARCHAR(255) NOT NULL, -- Clave de seguridad de 4 dígitos para cancelar alertas
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla TIPO_INCIDENCIA (Catálogo de emergencias)
CREATE TABLE IF NOT EXISTS tipo_incidencia (
    id_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- 3. Tabla ESTADO_REPORTE (Únicamente 2 estados)
CREATE TABLE IF NOT EXISTS estado_reporte (
    id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- 4. Tabla REPORTE (Incidencias generadas)
CREATE TABLE IF NOT EXISTS reporte (
    id_reporte BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona BIGINT REFERENCES persona(id_persona) ON DELETE CASCADE,
    id_tipo INT REFERENCES tipo_incidencia(id_tipo),
    id_estado INT REFERENCES estado_reporte(id_estado) DEFAULT 1,
    fecha_hora TIMESTAMPTZ DEFAULT NOW(),
    descripcion TEXT,
    direccion_texto VARCHAR(255), -- Dirección de referencia donde se originó la alerta
    fotos JSONB DEFAULT '[]'::jsonb
);

-- 5. Tabla UBICACION (Rastreo GPS en tiempo real - sin velocidad)
CREATE TABLE IF NOT EXISTS ubicacion (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reporte BIGINT REFERENCES reporte(id_reporte) ON DELETE CASCADE,
    latitud DOUBLE PRECISION NOT NULL,
    longitud DOUBLE PRECISION NOT NULL,
    fecha_hora TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- ÍNDICES PARA CONSULTAS DE ALTA VELOCIDAD
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_persona_dni ON persona(dni);
CREATE INDEX IF NOT EXISTS idx_ubicacion_reporte ON ubicacion(id_reporte, fecha_hora DESC);
CREATE INDEX IF NOT EXISTS idx_reporte_fecha ON reporte(fecha_hora DESC);

-- ==============================================================================
-- DATOS INICIALES (SEEDS)
-- ==============================================================================

-- Tipos de incidencia con SECUESTRO incluido
INSERT INTO tipo_incidencia (id_tipo, nombre, descripcion) VALUES 
(1, 'ROBO', 'Asaltos, robos a mano armada o botón de pánico SOS'),
(2, 'ACCIDENTE', 'Accidentes vehiculares, atropellos o impacto detectado'),
(3, 'INCENDIO', 'Incendios, fugas de gas o fuego activo'),
(4, 'GRESCA', 'Peleas callejeras, disturbios o desorden público'),
(5, 'ASESINATO', 'Atentados, homicidios o violencia extrema'),
(6, 'SECUESTRO', 'Privación de la libertad o rapto (alta prioridad y GPS en vivo)'),
(7, 'PERSONALIZADO', 'Reporte con descripción libre y fotos/evidencias')
ON CONFLICT (id_tipo) DO UPDATE 
SET nombre = EXCLUDED.nombre, descripcion = EXCLUDED.descripcion;

-- Estados de reporte (Solo 2 estados solicitados)
INSERT INTO estado_reporte (id_estado, nombre, descripcion) VALUES 
(1, 'Enviado', 'Alerta procesada y despachada a la central de monitoreo'),
(2, 'No enviado', 'Alerta fallida por corte de red o error de conexión')
ON CONFLICT (id_estado) DO UPDATE 
SET nombre = EXCLUDED.nombre, descripcion = EXCLUDED.descripcion;

-- Ajustar los contadores automáticos de ID para evitar conflictos
SELECT setval(pg_get_serial_sequence('tipo_incidencia', 'id_tipo'), (SELECT MAX(id_tipo) FROM tipo_incidencia));
SELECT setval(pg_get_serial_sequence('estado_reporte', 'id_estado'), (SELECT MAX(id_estado) FROM estado_reporte));

-- ==============================================================================
-- HABILITAR REALTIME (Para ver el mapa y reportes en vivo en la Central)
-- ==============================================================================
ALTER PUBLICATION supabase_realtime ADD TABLE ubicacion;
ALTER PUBLICATION supabase_realtime ADD TABLE reporte;
