-- ==============================================================================
-- ALERTA CIUDADANA - SPRINT 4: CONTROLES DE SEGURIDAD (SUPABASE / POSTGRESQL)
-- Unidad 02: Autenticación, Autorización y Cifrado
-- Cumple con: HU-SEG-01, HU-SEG-02, HU-SEG-04, HU-SEG-06, HU-SEG-07, HU-SEG-09
-- ==============================================================================

-- 1. Asegurar extensión pgcrypto para generación de UUIDs y hashes seguros
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 2. Asegurar estructura de PERSONA con password_hash y pin_hash (HU-SEG-06)
CREATE TABLE IF NOT EXISTS persona (
    id_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(15) UNIQUE NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL DEFAULT '',
    telefono VARCHAR(20) NOT NULL,
    direccion VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL, -- Hash bcrypt (cost factor 10-12)
    pin_hash VARCHAR(255) NOT NULL,      -- Hash bcrypt para PIN secreto de 4 dígitos
    rol VARCHAR(20) NOT NULL DEFAULT 'ciudadano', -- HU-SEG-05 (ciudadano / administrador)
    intentos_fallidos INT NOT NULL DEFAULT 0,    -- HU-SEG-03 (control de fuerza bruta)
    bloqueado_hasta TIMESTAMPTZ,                 -- HU-SEG-03 (bloqueo temporal 15 min)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla CODIGO_OTP (HU-SEG-01: Verificación OTP de 6 dígitos por WhatsApp)
CREATE TABLE IF NOT EXISTS codigo_otp (
    id_otp BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dni VARCHAR(15) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    codigo VARCHAR(6) NOT NULL,
    expira_en TIMESTAMPTZ NOT NULL, -- Validez de 5 minutos
    usado BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_otp_dni_tel ON codigo_otp(dni, telefono, expira_en);

-- 4. Tabla SESION_USUARIO (HU-SEG-02: Sesión persistente con token único revocable)
CREATE TABLE IF NOT EXISTS sesion_usuario (
    id_sesion UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_persona BIGINT REFERENCES persona(id_persona) ON DELETE CASCADE,
    dni VARCHAR(15) NOT NULL,
    token_jwt TEXT NOT NULL,
    dispositivo_info VARCHAR(255),
    revocado BOOLEAN NOT NULL DEFAULT FALSE, -- Revocable ante reporte de robo
    expira_en TIMESTAMPTZ NOT NULL,          -- 30 a 90 días de duración
    created_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_sesion_dni ON sesion_usuario(dni, revocado, expira_en);

-- 5. Tabla TIPO_INCIDENCIA
CREATE TABLE IF NOT EXISTS tipo_incidencia (
    id_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- 6. Tabla ESTADO_REPORTE
CREATE TABLE IF NOT EXISTS estado_reporte (
    id_estado INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255)
);

-- 7. Tabla REPORTE (HU-SEG-09: Integridad del reporte)
CREATE TABLE IF NOT EXISTS reporte (
    id_reporte BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_persona BIGINT REFERENCES persona(id_persona) ON DELETE CASCADE,
    id_tipo INT REFERENCES tipo_incidencia(id_tipo),
    id_estado INT REFERENCES estado_reporte(id_estado) DEFAULT 1,
    fecha_hora TIMESTAMPTZ DEFAULT NOW(),
    descripcion TEXT,
    direccion_texto VARCHAR(255),
    fotos JSONB DEFAULT '[]'::jsonb
);

-- 8. Tabla UBICACION (Rastreo GPS en tiempo real)
CREATE TABLE IF NOT EXISTS ubicacion (
    id_ubicacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reporte BIGINT REFERENCES reporte(id_reporte) ON DELETE CASCADE,
    latitud DOUBLE PRECISION NOT NULL,
    longitud DOUBLE PRECISION NOT NULL,
    fecha_hora TIMESTAMPTZ DEFAULT NOW()
);

-- ==============================================================================
-- HU-SEG-04 & HU-SEG-09: ROW LEVEL SECURITY (RLS) Y POLÍTICAS DE ACCESO
-- ==============================================================================

-- Activar RLS en todas las tablas
ALTER TABLE persona ENABLE ROW LEVEL SECURITY;
ALTER TABLE codigo_otp ENABLE ROW LEVEL SECURITY;
ALTER TABLE sesion_usuario ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipo_incidencia ENABLE ROW LEVEL SECURITY;
ALTER TABLE estado_reporte ENABLE ROW LEVEL SECURITY;
ALTER TABLE reporte ENABLE ROW LEVEL SECURITY;
ALTER TABLE ubicacion ENABLE ROW LEVEL SECURITY;

-- Limpiar políticas anteriores si existían
DROP POLICY IF EXISTS "tipo_incidencia_lectura" ON tipo_incidencia;
DROP POLICY IF EXISTS "estado_reporte_lectura" ON estado_reporte;
DROP POLICY IF EXISTS "reporte_insert_policy" ON reporte;
DROP POLICY IF EXISTS "reporte_select_policy" ON reporte;
DROP POLICY IF EXISTS "reporte_block_update" ON reporte;
DROP POLICY IF EXISTS "reporte_block_delete" ON reporte;
DROP POLICY IF EXISTS "ubicacion_insert_policy" ON ubicacion;
DROP POLICY IF EXISTS "ubicacion_select_policy" ON ubicacion;
DROP POLICY IF EXISTS "persona_anon_access" ON persona;
DROP POLICY IF EXISTS "otp_anon_access" ON codigo_otp;
DROP POLICY IF EXISTS "sesion_anon_access" ON sesion_usuario;

-- Políticas de Catálogos (Lectura pública)
CREATE POLICY "tipo_incidencia_lectura" ON tipo_incidencia FOR SELECT USING (true);
CREATE POLICY "estado_reporte_lectura" ON estado_reporte FOR SELECT USING (true);

-- HU-SEG-09: REPORTE SOLO PERMITE INSERT Y SELECT (UPDATE Y DELETE BLOQUEADOS PARA LA APP)
CREATE POLICY "reporte_insert_policy" ON reporte FOR INSERT WITH CHECK (true);
CREATE POLICY "reporte_select_policy" ON reporte FOR SELECT USING (true);
-- No se crean políticas para UPDATE ni DELETE en la tabla reporte.
-- Al tener RLS activo, PostgreSQL bloquea automáticamente cualquier intento de UPDATE o DELETE para roles anónimos/autenticados.

-- Políticas para UBICACION (Rastreo GPS continuo: Solo INSERT y SELECT)
CREATE POLICY "ubicacion_insert_policy" ON ubicacion FOR INSERT WITH CHECK (true);
CREATE POLICY "ubicacion_select_policy" ON ubicacion FOR SELECT USING (true);

-- Políticas para PERSONA, OTP y SESION (Gestionadas mediante Backend / Edge Function segura con service_role)
CREATE POLICY "persona_anon_access" ON persona FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "otp_anon_access" ON codigo_otp FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "sesion_anon_access" ON sesion_usuario FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- DATOS INICIALES (SEEDS)
-- ==============================================================================
INSERT INTO tipo_incidencia (id_tipo, nombre, descripcion) VALUES 
(1, 'ROBO', 'Asaltos, robos a mano armada o botón de pánico SOS'),
(2, 'ACCIDENTE', 'Accidentes vehiculares, atropellos o impacto detectado'),
(3, 'INCENDIO', 'Incendios, fugas de gas o fuego activo'),
(4, 'GRESCA', 'Peleas callejeras, disturbios o desorden público'),
(5, 'ASESINATO', 'Atentados, homicidios o violencia extrema'),
(6, 'SECUESTRO', 'Privación de la libertad o rapto (alta prioridad y GPS en vivo)'),
(7, 'PERSONALIZADO', 'Reporte con descripción libre y fotos/evidencias')
ON CONFLICT (id_tipo) DO UPDATE 
SET nombre = EXCLUDED.nombre, descripcion = EXCLUDED.descripcion;

INSERT INTO estado_reporte (id_estado, nombre, descripcion) VALUES 
(1, 'Enviado', 'Alerta procesada y despachada a la central de monitoreo'),
(2, 'No enviado', 'Alerta fallida por corte de red o error de conexión')
ON CONFLICT (id_estado) DO UPDATE 
SET nombre = EXCLUDED.nombre, descripcion = EXCLUDED.descripcion;

SELECT setval(pg_get_serial_sequence('tipo_incidencia', 'id_tipo'), (SELECT MAX(id_tipo) FROM tipo_incidencia));
SELECT setval(pg_get_serial_sequence('estado_reporte', 'id_estado'), (SELECT MAX(id_estado) FROM estado_reporte));

-- ==============================================================================
-- USUARIO DE PRUEBA OFICIAL (HU-SEG-06: Hashes Bcrypt costo 10 con pgcrypto)
-- ==============================================================================
INSERT INTO persona (dni, nombres, apellidos, telefono, direccion, password_hash, pin_hash, rol)
VALUES (
    '12345678',
    'Juan',
    'Pérez Test',
    '+51987654321',
    'Av. San Martín 123, Pisco',
    crypt('Alerta2026!', gen_salt('bf', 10)),
    crypt('1234', gen_salt('bf', 10)),
    'ciudadano'
)
ON CONFLICT (dni) DO UPDATE
SET 
    password_hash = crypt('Alerta2026!', gen_salt('bf', 10)),
    pin_hash = crypt('1234', gen_salt('bf', 10)),
    intentos_fallidos = 0,
    bloqueado_hasta = NULL;
